#nullable enable

namespace Dataplat.Dbatools.Commands;

/// <summary>Hop script constants for BackupDbaDatabaseCommand (400-line file rule split;
/// generated by migration/tools/Build-W3004Partials.py from the verbatim source fragments -
/// regenerate, never hand-edit).</summary>
public sealed partial class BackupDbaDatabaseCommand
{
    private const string ProcessScriptHead = """
param($SqlInstance, $SqlCredential, $Database, $ExcludeDatabase, $Path, $FilePath, $IncrementPrefix, $ReplaceInName, $NoAppendDbNameInPath, $CopyOnly, $Type, $CreateFolder, $FileCount, $CompressBackup, $Checksum, $Verify, $MaxTransferSize, $BlockSize, $BufferCount, $StorageBaseUrl, $StorageCredential, $StorageRegion, $NoRecovery, $BuildPath, $WithFormat, $Initialize, $SkipTapeHeader, $TimeStampFormat, $IgnoreFileChecks, $OutputScriptOnly, $EncryptionAlgorithm, $EncryptionCertificate, $Description, $InputObject, $EnableException, $__state, $__hopInterrupted, $__realBoundParameters, $__realCmdlet, $__boundWhatIf, $__boundConfirm, $__boundVerbose, $__boundDebug)
$__commonParameters = @{}
if ($null -ne $__boundWhatIf) { $__commonParameters.WhatIf = [bool]$__boundWhatIf }
if ($null -ne $__boundConfirm) { $__commonParameters.Confirm = [bool]$__boundConfirm }
if ($null -ne $__boundVerbose) { $__commonParameters.Verbose = [bool]$__boundVerbose }
if ($null -ne $__boundDebug -and $PSVersionTable.PSVersion.Major -lt 7) { $__commonParameters.Debug = [bool]$__boundDebug }
$__dbatoolsModule = Get-Module -Name dbatools | Where-Object ModuleType -eq "Script" | Select-Object -First 1
& $__dbatoolsModule {
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = "Medium")]
    param($SqlInstance, $SqlCredential, [object[]]$Database, [object[]]$ExcludeDatabase, [string[]]$Path, [string]$FilePath, $IncrementPrefix, $ReplaceInName, $NoAppendDbNameInPath, $CopyOnly, [string]$Type, $CreateFolder, [int]$FileCount, $CompressBackup, $Checksum, $Verify, [int]$MaxTransferSize, [int]$BlockSize, [int]$BufferCount, [string[]]$StorageBaseUrl, [string]$StorageCredential, [string]$StorageRegion, $NoRecovery, $BuildPath, $WithFormat, $Initialize, $SkipTapeHeader, [string]$TimeStampFormat, $IgnoreFileChecks, $OutputScriptOnly, [string]$EncryptionAlgorithm, [string]$EncryptionCertificate, [string]$Description, [object[]]$InputObject, $EnableException, $__state, $__hopInterrupted, $__realBoundParameters, $__realCmdlet, $__boundWhatIf, $__boundConfirm, $__boundVerbose, $__boundDebug)
    if ($null -ne $__boundDebug -and $PSVersionTable.PSVersion.Major -ge 7) { $DebugPreference = $(if ($__boundDebug) { "Continue" } else { "SilentlyContinue" }) }
    if ($__hopInterrupted) { return }
    # $PSBoundParameters fidelity (plan item 3): positional hop binding marks EVERYTHING
    # bound; prune to the caller's real set so Test-Bound, ContainsKey('CompressBackup') and
    # the $PSBoundParameters.Path/.FilePath reads/writes run verbatim.
    foreach ($__k in @($PSBoundParameters.Keys)) { if (-not $__realBoundParameters.ContainsKey($__k)) { $null = $PSBoundParameters.Remove($__k) } }
    # Re-apply the begin/prior-record $PSBoundParameters.Path/.FilePath rewires with KEY-PRESENCE
    # fidelity (codex r3): a null-valued-but-present key restores as present, an absent key stays absent.
    if ($__state.psbpHasPath) { $PSBoundParameters["Path"] = $__state.psbpPath } else { $null = $PSBoundParameters.Remove("Path") }
    if ($__state.psbpHasFilePath) { $PSBoundParameters["FilePath"] = $__state.psbpFilePath } else { $null = $PSBoundParameters.Remove("FilePath") }
    # Restore the carried stale-able locals (plan item 2 - the full set, both directions).
    $TimeStampFormat = $__state.TimeStampFormat
    $BlockSize = $__state.BlockSize
    $MaxTransferSize = $__state.MaxTransferSize
    $isS3Backup = $__state.isS3Backup
    $Path = $__state.Path
    $FilePath = $__state.FilePath
    $FileCount = $__state.FileCount
    $StorageBaseUrl = $__state.StorageBaseUrl
    $IgnoreFileChecks = $__state.IgnoreFileChecks
    $Initialize = $__state.Initialize
    $SkipTapeHeader = $__state.SkipTapeHeader
    $NoAppendDbNameInPath = $__state.NoAppendDbNameInPath
    $CopyOnly = $__state.CopyOnly
    $isdir = $__state.isdir
    $failreason = $__state.failreason
    $Description = $__state.Description
    $HeaderInfo = $__state.HeaderInfo
    # InputObject: begin builds the batch ONLY in the Pipe set (SqlInstance bound); piped
    # NoPipe records bind their own value per record exactly like the engine (source 431/465).
    if ($__realBoundParameters.ContainsKey("SqlInstance")) { $InputObject = $__state.InputObject }
        # this had to be a function. making it a variable killed something. I'm guessing scoping issues
        Function Convert-BackupPath ($object) {
            if ($object -match "/|\\") {
                if ($isdestlinux -and $object) {
                    $object = $object.Replace("\", "/")
                } elseif ($transformedbackupfolder) {
                    $object = $object.Replace("/", "\")
                }
            }
            $object
        }
    # Dot-sourced so the plain Stop-Function + return sites still reach the sentinel (W1-108).
    . {
        if (Test-FunctionInterrupt) { return }
        if ($IsMacOS -or $IsLinux) {
            $nonwindows = $true
        }
        if (-not $SqlInstance -and -not $InputObject) {
            Stop-Function -Message "You must specify a server and database or pipe some databases" -FunctionName Backup-DbaDatabase
            return
        }

        Write-Message -Level Verbose -Message "$($InputObject.Count) database to backup" -FunctionName Backup-DbaDatabase

        if ($Database) {
            $InputObject = $InputObject | Where-Object Name -in $Database
        }

        if ($ExcludeDatabase) {
            $InputObject = $InputObject | Where-Object Name -notin $ExcludeDatabase
        }

        if ($InputObject.count -eq 0) {
            Write-Message -Level Warning -Message "No databases match the request for backups" -FunctionName Backup-DbaDatabase
        }

        $topProgressId = Get-Random
        $topProgressTarget = $InputObject.Count
        $topProgressNumber = 0
        foreach ($db in $InputObject) {
            if ($FilePath -and -not $Path) {
                try {
                    # cl gave a bad example in dbatools in a month of lunches, accommodate it
                    Write-Message -Level Verbose -Message "Checking to see if FilePath is a directory" -FunctionName Backup-DbaDatabase
                    $isdir = ($db.Query("EXEC master.dbo.xp_fileexist '$FilePath'")).Item(1)
                } catch {
                    # ignore
                }

                if ($isdir) {
                    Write-Message -Level Verbose -Message "Ooops, FilePath is a directory, using it as the backup path" -FunctionName Backup-DbaDatabase
                    $PSBoundParameters.Path = $FilePath
                    $Path = $FilePath
                    $PSBoundParameters.FilePath = $null
                    $FilePath = $null
                }
            }
            $topProgressPercent = [int]($topProgressNumber * 100 / $topProgressTarget)
            $topProgressNumber++
            if (-not $__realCmdlet.MyInvocation.ExpectingInput) {
                # Only when the databases to be processed are not piped to the command
                Write-Progress -Id $topProgressId -Activity "Backing up database $topProgressNumber of $topProgressTarget" -PercentComplete $topProgressPercent -Status ([System.String]::Format("Progress: {0} %", $topProgressPercent))
            }

            $ProgressId = Get-Random
            $failures = @()
            $dbName = $db.Name
            $server = $db.Parent
            $null = $server.Refresh()
            $isdestlinux = Test-HostOSLinux -SqlInstance $server

            if (Test-Bound 'EncryptionAlgorithm') {
                if (!((Test-Bound 'EncryptionCertificate') -xor (Test-Bound 'EncryptionKey'))) {
                    Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                    Stop-Function -Message 'EncryptionCertifcate and EncryptionKey are mutually exclusive, only provide on of them' -FunctionName Backup-DbaDatabase
                    return
                } else {
                    $encryptionOptions = New-Object Microsoft.SqlServer.Management.Smo.BackupEncryptionOptions
                    if (Test-Bound 'EncryptionCertificate') {
                        # PORT (contracts.md section 2, owner-locked): inline SMO lookup replaces the
                        # security-module Get-DbaDbCertificate call (source :532) - same null-when-missing contract.
                        $tCertCheck = $server.Databases["master"].Certificates | Where-Object Name -eq $EncryptionCertificate
                        if ($null -eq $tCertCheck) {
                            Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                            Stop-Function -Message "Certificate $EncryptionCertificate does not exist on $server so cannot be used for backups" -FunctionName Backup-DbaDatabase
                            return
                        } else {
                            $encryptionOptions.encryptorType = [Microsoft.SqlServer.Management.Smo.BackupEncryptorType]::ServerCertificate
                            $encryptionOptions.encryptorName = $EncryptionCertificate
                            $encryptionOptions.Algorithm = [Microsoft.SqlServer.Management.Smo.BackupEncryptionAlgorithm]::$EncryptionAlgorithm
                        }
                    }
                    if (Test-Bound 'EncryptionKey') {
                        # Should not end up here until Key encryption in implemented
                        # PORT (contracts.md section 2, owner-locked): inline SMO lookup replaces the dead
                        # Get-DbaDbAsymmetricKey call (source :545, unreachable - EncryptionKey is never a parameter).
                        $tKeyCheck = $server.Databases["master"].AsymmetricKeys | Where-Object Name -eq $EncrytptionKey
                        if ($null -eq $tKeyCheck) {
                            Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                            Stop-Function -Message "AsymmetricKey $Encryptionkey does not exist on $server so cannot be used for backups" -FunctionName Backup-DbaDatabase
                            return
                        } else {
                            $encryptionOptions.encryptorType = [Microsoft.SqlServer.Management.Smo.BackupEncryptorType]::ServerAsymmetricKey
                            $encryptionOptions.encryptorName = $EncryptionKey
                            $encryptionOptions.Algorithm = [Microsoft.SqlServer.Management.Smo.BackupEncryptionAlgorithm]::$EncryptionAlgorithm
                        }
                    }
                }
            }


            if ( (Test-Bound StorageBaseUrl -Not) -and (Test-Bound Path -Not) -and $FilePath -ne 'NUL') {
                Write-Message -Message 'No backup folder passed in, setting it to instance default' -Level Verbose -FunctionName Backup-DbaDatabase
                $Path = (Get-DbaDefaultPath -SqlInstance $server).Backup
                if ($Path) {
                    # it's very picky, don't cut corners
                    $lastchar = $Path.substring($Path.length - 1, 1)
                    if ($lastchar -eq "/" -or $lastchar -eq "\") {
                        $Path = $Path.TrimEnd("/")
                        $Path = $Path.TrimEnd("\")
                    }
                }
            }

            # Validate MaxTransferSize for non-S3 backups (S3 validation is done later in the S3 block)
            $isS3Url = $null -ne $StorageBaseUrl -and $StorageBaseUrl[0] -match "^s3://"
            if ($MaxTransferSize -and -not $isS3Url) {
                if (($MaxTransferSize % 64kb) -ne 0 -or $MaxTransferSize -gt 4mb) {
                    Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                    Stop-Function -Message "MaxTransferSize value must be a multiple of 64KB and no greater than 4MB" -FunctionName Backup-DbaDatabase
                    return
                }
            }

            if ($BlockSize) {
                if ($BlockSize -notin (0.5kb, 1kb, 2kb, 4kb, 8kb, 16kb, 32kb, 64kb)) {
                    Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                    Stop-Function -Message "Block size must be one of 0.5kb,1kb,2kb,4kb,8kb,16kb,32kb,64kb" -FunctionName Backup-DbaDatabase
                    return
                }
            }

            if ($null -ne $StorageBaseUrl) {
                # Detect if this is S3 or Azure storage
                $isS3Backup = $StorageBaseUrl[0] -match "^s3://"

                if ($isS3Backup) {
                    # S3-compatible object storage (SQL Server 2022+)
                    if ($server.VersionMajor -lt 16) {
                        Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                        Stop-Function -Message "S3 backup requires SQL Server 2022 or later. Current version: $($server.Version)" -FunctionName Backup-DbaDatabase
                        return
                    }

                    # Validate MaxTransferSize for S3 (must be between 5MB and 20MB)
                    if ($MaxTransferSize) {
                        if (($MaxTransferSize % 64kb) -ne 0 -or $MaxTransferSize -lt 5mb -or $MaxTransferSize -gt 20mb) {
                            Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                            Stop-Function -Message "MaxTransferSize for S3 backups must be a multiple of 64KB and between 5MB and 20MB" -FunctionName Backup-DbaDatabase
                            return
                        }
                    } else {
                        # Set default MaxTransferSize for S3 if not specified (10MB is a good default)
                        $MaxTransferSize = 10mb
                        Write-Message -Level Verbose -Message "S3 backup detected, setting default MaxTransferSize to 10MB" -FunctionName Backup-DbaDatabase
                    }

                    # Validate StorageRegion if specified with non-S3 URL
                    if ((Test-Bound 'StorageRegion') -and -not $isS3Backup) {
                        Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                        Stop-Function -Message "StorageRegion can only be specified with S3 URLs" -FunctionName Backup-DbaDatabase
                        return
                    }

                    # S3 URLs should not have trailing slash trimmed the same way
                    $StorageBaseUrl = $StorageBaseUrl | ForEach-Object { $_.TrimEnd("/") }
                } else {
                    # Azure Blob Storage
                    $StorageBaseUrl = $StorageBaseUrl.Trim("/")

                    # Validate StorageRegion not used with Azure
                    if (Test-Bound 'StorageRegion') {
                        Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                        Stop-Function -Message "StorageRegion can only be specified with S3 URLs, not Azure storage" -FunctionName Backup-DbaDatabase
                        return
                    }
                }

                if ('' -ne $StorageCredential) {
                    Write-Message -Message "Storage credential name passed in, will proceed assuming it's valid" -Level Verbose -FunctionName Backup-DbaDatabase
                    if (-not $isS3Backup) {
""";
}
