#nullable enable

namespace Dataplat.Dbatools.Commands;

/// <summary>Hop script constants for BackupDbaDatabaseCommand (400-line file rule split;
/// generated by migration/tools/Build-W3004Partials.py from the verbatim source fragments -
/// regenerate, never hand-edit).</summary>
public sealed partial class BackupDbaDatabaseCommand
{
    private const string BeginScript = """
param($SqlInstance, $SqlCredential, $Database, $ExcludeDatabase, $Path, $FilePath, $IncrementPrefix, $ReplaceInName, $NoAppendDbNameInPath, $CopyOnly, $Type, $CreateFolder, $FileCount, $CompressBackup, $Checksum, $Verify, $MaxTransferSize, $BlockSize, $BufferCount, $StorageBaseUrl, $StorageCredential, $StorageRegion, $NoRecovery, $BuildPath, $WithFormat, $Initialize, $SkipTapeHeader, $TimeStampFormat, $IgnoreFileChecks, $OutputScriptOnly, $EncryptionAlgorithm, $EncryptionCertificate, $Description, $InputObject, $EnableException, $__realBoundParameters, $__realCmdlet, $__boundVerbose, $__boundDebug)
$__commonParameters = @{}
if ($null -ne $__boundVerbose) { $__commonParameters.Verbose = [bool]$__boundVerbose }
if ($null -ne $__boundDebug -and $PSVersionTable.PSVersion.Major -lt 7) { $__commonParameters.Debug = [bool]$__boundDebug }
$__dbatoolsModule = Get-Module -Name dbatools | Where-Object ModuleType -eq "Script" | Select-Object -First 1
& $__dbatoolsModule {
    [CmdletBinding()]
    param($SqlInstance, $SqlCredential, [object[]]$Database, [object[]]$ExcludeDatabase, [string[]]$Path, [string]$FilePath, $IncrementPrefix, $ReplaceInName, $NoAppendDbNameInPath, $CopyOnly, [string]$Type, $CreateFolder, [int]$FileCount, $CompressBackup, $Checksum, $Verify, [int]$MaxTransferSize, [int]$BlockSize, [int]$BufferCount, [string[]]$StorageBaseUrl, [string]$StorageCredential, [string]$StorageRegion, $NoRecovery, $BuildPath, $WithFormat, $Initialize, $SkipTapeHeader, [string]$TimeStampFormat, $IgnoreFileChecks, $OutputScriptOnly, [string]$EncryptionAlgorithm, [string]$EncryptionCertificate, [string]$Description, [object[]]$InputObject, $EnableException, $__realBoundParameters, $__realCmdlet, $__boundVerbose, $__boundDebug)
    if ($null -ne $__boundDebug -and $PSVersionTable.PSVersion.Major -ge 7) { $DebugPreference = $(if ($__boundDebug) { "Continue" } else { "SilentlyContinue" }) }
    # $PSBoundParameters fidelity (plan item 3): positional hop binding marks EVERYTHING
    # bound; prune to the caller's real set so Test-Bound, ContainsKey('CompressBackup') and
    # the $PSBoundParameters.Path/.FilePath reads/writes run verbatim.
    foreach ($__k in @($PSBoundParameters.Keys)) { if (-not $__realBoundParameters.ContainsKey($__k)) { $null = $PSBoundParameters.Remove($__k) } }
    $__psbpForBody = $PSBoundParameters
    # Dot-sourced so the five plain Stop-Function + return sites still reach the sentinel (W1-108).
    . {
    $PSBoundParameters = $__psbpForBody
        # This is here ready to go when get EKM working so we can do encrption with asymmetric encryption.
        $EncryptionKey = $null

        if (-not (Test-Bound 'TimeStampFormat')) {
            Write-Message -Message 'Setting Default timestampformat' -Level Verbose -FunctionName Backup-DbaDatabase
            $TimeStampFormat = "yyyyMMddHHmm"
        }

        if ((Test-Bound 'StorageBaseUrl') -and (Test-Bound 'CreateFolder')) {
            Stop-Function -Message 'CreateFolder cannot be specified with a cloud storage backup, the container/bucket must exist and be referenced by the URL' -FunctionName Backup-DbaDatabase
            return
        }

        # Determine if this is an S3 backup (S3 URLs start with s3://)
        $isS3Backup = (Test-Bound 'StorageBaseUrl') -and ($StorageBaseUrl | Where-Object { $_ -match "^s3://" })

        if ((Test-Bound 'StorageCredential') -and (Test-Bound 'BlockSize') -and -not $isS3Backup) {
            Write-Message -Level Warning -Message 'BlockSize cannot be specified when backing up to an Azure page blob, ignoring' -FunctionName Backup-DbaDatabase
            $BlockSize = $null
        }

        if ((Test-Bound 'StorageCredential') -and (Test-Bound 'MaxTransferSize') -and -not $isS3Backup) {
            Write-Message -Level Warning -Message 'MaxTransferSize cannot be specified when backing up to an Azure page blob, ignoring' -FunctionName Backup-DbaDatabase
            $MaxTransferSize = $null
        }

        if ($isS3Backup -and (Test-Bound 'MaxTransferSize') -and -not (Test-Bound 'CompressBackup')) {
            Stop-Function -Message 'CompressBackup must be enabled when specifying MaxTransferSize for S3 backups' -FunctionName Backup-DbaDatabase
            return
        }

        if ((Test-Bound 'StorageRegion') -and -not (Test-Bound 'StorageBaseUrl')) {
            Stop-Function -Message 'StorageRegion can only be specified when using StorageBaseUrl with an S3 URL' -FunctionName Backup-DbaDatabase
            return
        }

        if ($SqlInstance) {
            try {
                $server = Connect-DbaInstance -SqlInstance $SqlInstance -SqlCredential $SqlCredential -AzureUnsupported -Database master
            } catch {
                Stop-Function -Message "Failure" -Category ConnectionError -ErrorRecord $_ -Target $SqlInstance -FunctionName Backup-DbaDatabase
                return
            }

            if ($FilePath -and -not $Path) {
                try {
                    # cl gave a bad example in dbatools in a month of lunches, accommodate it
                    Write-Message -Level Verbose -Message "Checking to see if FilePath is a directory" -FunctionName Backup-DbaDatabase
                    $isdir = ($server.Query("EXEC master.dbo.xp_fileexist '$FilePath'")).Item(1)
                } catch {
                    # ignore
                }

                if ($isdir) {
                    Write-Message -Level Verbose -Message "Ooops, FilePath is a directory, using it as the backup path" -FunctionName Backup-DbaDatabase
                    $PSBoundParameters.Path = $FilePath
                    $Path = $FilePath
                    $PSBoundParameters.FilePath = $null
                    $FilePath = $null
                }
            }

            $InputObject = $server.Databases | Where-Object Name -ne 'tempdb'

            if ($Database) {
                $InputObject = $InputObject | Where-Object Name -in $Database
            }

            if ($ExcludeDatabase) {
                $InputObject = $InputObject | Where-Object Name -notin $ExcludeDatabase
            }

            if ($Path.Count -gt 1) {
                Write-Message -Level Verbose -Message "Multiple Backup Directories, striping" -FunctionName Backup-DbaDatabase
                $FileCount = $Path.Count
            }

            if ($InputObject.Count -gt 1 -and $FilePath -ne '' -and $True -ne $ReplaceInName) {
                Stop-Function -Message "1 BackupFile specified, but more than 1 database." -FunctionName Backup-DbaDatabase
                return
            }
        }
    }
    @{ __w3004State = @{ TimeStampFormat = $TimeStampFormat; BlockSize = $BlockSize; MaxTransferSize = $MaxTransferSize; isS3Backup = $isS3Backup; Path = $Path; FilePath = $FilePath; FileCount = $FileCount; StorageBaseUrl = $StorageBaseUrl; IgnoreFileChecks = $IgnoreFileChecks; Initialize = $Initialize; SkipTapeHeader = $SkipTapeHeader; NoAppendDbNameInPath = $NoAppendDbNameInPath; CopyOnly = $CopyOnly; isdir = $isdir; failreason = $failreason; Description = $Description; HeaderInfo = $HeaderInfo; InputObject = $InputObject; psbpHasPath = $PSBoundParameters.ContainsKey("Path"); psbpPath = $PSBoundParameters["Path"]; psbpHasFilePath = $PSBoundParameters.ContainsKey("FilePath"); psbpFilePath = $PSBoundParameters["FilePath"]; interrupted = (Test-FunctionInterrupt) } }
} $SqlInstance $SqlCredential $Database $ExcludeDatabase $Path $FilePath $IncrementPrefix $ReplaceInName $NoAppendDbNameInPath $CopyOnly $Type $CreateFolder $FileCount $CompressBackup $Checksum $Verify $MaxTransferSize $BlockSize $BufferCount $StorageBaseUrl $StorageCredential $StorageRegion $NoRecovery $BuildPath $WithFormat $Initialize $SkipTapeHeader $TimeStampFormat $IgnoreFileChecks $OutputScriptOnly $EncryptionAlgorithm $EncryptionCertificate $Description $InputObject $EnableException $__realBoundParameters $__realCmdlet $__boundVerbose $__boundDebug @__commonParameters 3>&1 2>&1
""";
}
