#nullable enable

namespace Dataplat.Dbatools.Commands;

/// <summary>Hop script constants for BackupDbaDatabaseCommand (400-line file rule split;
/// generated by migration/tools/Build-W3004Partials.py from the verbatim source fragments -
/// regenerate, never hand-edit).</summary>
public sealed partial class BackupDbaDatabaseCommand
{
    private const string ProcessScriptMid = """
                    Write-Message -Message "Storage credential name passed in, will proceed assuming it's valid" -Level Verbose -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                    if (-not $isS3Backup) {
                        # Azure page blob with credential = single file only
                        $FileCount = 1
                    }
                } else {
                    foreach ($baseUrl in $StorageBaseUrl) {
                        if ($isS3Backup) {
                            # S3 credential name should match the S3 URL path
                            $credentialName = $baseUrl
                            Write-Message -Message "S3 URL detected, testing for S3 credential" -Level Verbose -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                        } else {
                            # Azure SAS credential logic
                            $base = $baseUrl -split "/"
                            if ( $base.Count -gt 4) {
                                Write-Message "Storage URL contains a folder" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                                $credentialName = $base[0] + "//" + $base[2] + "/" + $base[3]
                            } else {
                                # URL is just the container, use it as-is for credential name
                                $credentialName = $baseUrl
                            }
                            Write-Message -Message "Azure URL and no credential, testing for SAS credential" -Level Verbose -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                        }
                        if (Get-DbaCredential -SqlInstance $server -Name $credentialName) {
                            Write-Message -Message "Found a matching backup credential" -Level Verbose -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                        } else {
                            Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                            if ($isS3Backup) {
                                Stop-Function -Message "You must provide the credential name for S3 storage or create a credential matching the S3 URL" -FunctionName Backup-DbaDatabase
                            } else {
                                Stop-Function -Message "You must provide the credential name for the Azure Storage Account" -FunctionName Backup-DbaDatabase
                            }
                            return
                        }
                    }
                }
                if ($StorageBaseUrl.Count -gt 1 -or $FileCount -eq 0) {
                    $FileCount = $StorageBaseUrl.count
                }
                $Path = $StorageBaseUrl
            }

            if ($OutputScriptOnly) {
                $IgnoreFileChecks = $true
            }

            if ($null -eq $PSBoundParameters.Path -and $PSBoundParameters.FilePath -ne 'NUL' -and $server.VersionMajor -eq 8) {
                Write-Message -Message 'No backup folder passed in, setting it to instance default' -Level Verbose -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                $Path = (Get-DbaDefaultPath -SqlInstance $server).Backup
            }

            if ($dbName -eq "tempdb") {
                Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                Stop-Function -Message "Backing up tempdb not supported" -Continue -FunctionName Backup-DbaDatabase
            }

            if (-not $db.IsAccessible) {
                Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                Stop-Function -Message "Database $dbName is not accessible. Cannot perform backup." -Continue -Target $db -FunctionName Backup-DbaDatabase
            }

            if ('Normal' -notin ($db.Status -split ',')) {
                Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                Stop-Function -Message "Database status not Normal. $dbName skipped." -Continue -FunctionName Backup-DbaDatabase
            }

            if ($db.DatabaseSnapshotBaseName) {
                Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                Stop-Function -Message "Backing up snapshots not supported. $dbName skipped." -Continue -FunctionName Backup-DbaDatabase
            }

            Write-Message -Level Verbose -Message "Backup database $db" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"

            if ($null -eq $db.RecoveryModel) {
                $db.RecoveryModel = $server.Databases[$db.Name].RecoveryModel
                Write-Message -Level Verbose -Message "$dbName is in $($db.RecoveryModel) recovery model" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
            }

            # Fixes one-off cases of StackOverflowException crashes, see issue 1481
            $dbRecovery = $db.RecoveryModel.ToString()
            if ($dbRecovery -eq 'Simple' -and $Type -eq 'Log') {
                $failreason = "$db is in simple recovery mode, cannot take log backup"
                $failures += $failreason
                Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                Stop-Function -Message "$failreason" -Continue -Target $db -FunctionName Backup-DbaDatabase
            }

            $db.Refresh()
            $lastfull = $db.LastBackupDate.Year

            if ($Type -notin @("Database", "Full") -and $lastfull -eq 1) {
                $failreason = "$db does not have an existing full backup, cannot take log or differential backup"
                $failures += $failreason
                Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                Stop-Function -Message "$failreason" -Continue -Target $db -FunctionName Backup-DbaDatabase
            }

            if ($CopyOnly -ne $true) {
                $CopyOnly = $false
            }

            $server.ConnectionContext.StatementTimeout = 0
            $backup = New-Object Microsoft.SqlServer.Management.Smo.Backup
            $backup.Database = $db.Name
            if (Test-Bound -ParameterName Description) {
                if ($Description.Length -gt 255) {
                    Write-Message -Level Warning -Message 'Description is too long and will be truncated to 255 characters' -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                    $Description = $Description.Substring(0, 255)
                }
                $backup.BackupSetDescription = $Description
            }
            $Suffix = "bak"

            if ($null -ne $encryptionOptions) {
                $backup.EncryptionOption = $encryptionOptions
            }

            if ($PSBoundParameters.ContainsKey('CompressBackup')) {
                if ($CompressBackup) {
                    if ($db.EncryptionEnabled) {
                        # Newer versions of SQL Server automatically set the MAXTRANSFERSIZE to 128k
                        # so let's do that for people as well
                        $minVerForTDECompression = [version]'13.0.4446.0' #SQL Server 2016 CU 4
                        $flagTDESQLVersion = $minVerForTDECompression -le $Server.version
                        if (-not (Test-Bound 'MaxTransferSize')) {
                            $MaxTransferSize = 128kb
                        }
                        $flagCorrectMaxTransferSize = ($MaxTransferSize -gt 64kb)
                        if ($flagTDESQLVersion -and $flagCorrectMaxTransferSize) {
                            Write-Message -Level Verbose -Message "$dbName is enabled for encryption but will compress" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                            $backup.CompressionOption = [Microsoft.SqlServer.Management.Smo.BackupCompressionOptions]::On
                        } else {
                            Write-Message -Level Warning -Message "$dbName is enabled for encryption, will not compress" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                            $backup.CompressionOption = [Microsoft.SqlServer.Management.Smo.BackupCompressionOptions]::Off
                        }
                    } elseif ($server.Edition -like 'Express*' -or ($server.VersionMajor -eq 10 -and $server.VersionMinor -eq 0 -and $server.Edition -notlike '*enterprise*') -or $server.VersionMajor -lt 10) {
                        Write-Progress -Id $topProgressId -Activity 'Backup' -Completed
                        Stop-Function -Message "Compression is not supported with this version/edition of Sql Server" -Continue -Target $db -FunctionName Backup-DbaDatabase
                    } else {
                        Write-Message -Level Verbose -Message "Compression enabled" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                        $backup.CompressionOption = [Microsoft.SqlServer.Management.Smo.BackupCompressionOptions]::On
                    }
                } else {
                    Write-Message -Level Verbose -Message "Compression disabled" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                    $backup.CompressionOption = [Microsoft.SqlServer.Management.Smo.BackupCompressionOptions]::Off
                }
            } else {
                Write-Message -Level Verbose -Message "Using instance default backup compression setting" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                $backup.CompressionOption = [Microsoft.SqlServer.Management.Smo.BackupCompressionOptions]::Default
            }

            if ($Checksum) {
                $backup.Checksum = $true
            }

            if ($Type -in 'Diff', 'Differential') {
                Write-Message -Level VeryVerbose -Message "Creating differential backup" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                $SMOBackuptype = "Database"
                $backup.Incremental = $true
                $outputType = 'Differential'
                $gbhSwitch = @{'LastDiff' = $true }
            }
            $Backup.NoRecovery = $false
            if ($Type -eq "Log") {
                Write-Message -Level VeryVerbose -Message "Creating log backup" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                $Suffix = "trn"
                $OutputType = 'Log'
                $SMOBackupType = 'Log'
                $Backup.NoRecovery = $NoRecovery
                $gbhSwitch = @{'LastLog' = $true }
            }

            if ($Type -in 'Full', 'Database') {
                Write-Message -Level VeryVerbose -Message "Creating full backup" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                $SMOBackupType = "Database"
                $OutputType = 'Full'
                $gbhSwitch = @{'LastFull' = $true }
            }

            $backup.CopyOnly = $CopyOnly
            $backup.Action = $SMOBackupType
            if ($null -ne $StorageBaseUrl -and $null -ne $StorageCredential) {
                $backup.CredentialName = $StorageCredential
            }

            Write-Message -Level Verbose -Message "Building file name" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
            $BackupFinalName = ''
            $FinalBackupPath = @()
            $timestamp = Get-Date -Format $TimeStampFormat
            if ('NUL' -eq $FilePath) {
                $FinalBackupPath += 'NUL:'
                $IgnoreFileChecks = $true
            } elseif ('' -ne $FilePath) {
                $File = New-Object System.IO.FileInfo($FilePath)
                $BackupFinalName = $file.Name
                $suffix = $file.extension -Replace '^\.', ''
                if ( '' -ne (Split-Path $FilePath)) {
                    Write-Message -Level Verbose -Message "Fully qualified path passed in" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                    # Because of #7860, don't use [IO.Path]::GetFullPath on MacOS
                    if ($nonwindows -or $isdestlinux) {
                        $FinalBackupPath += $file.DirectoryName
                    } else {
                        $FinalBackupPath += [IO.Path]::GetFullPath($file.DirectoryName)
                    }
                }
            } else {
                Write-Message -Level VeryVerbose -Message "Setting filename - $timestamp" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
                $BackupFinalName = "$($dbName)_$timestamp.$suffix"
            }

            Write-Message -Level Verbose -Message "Building backup path" -FunctionName Backup-DbaDatabase -ModuleName "dbatools"
            if ($FinalBackupPath.Count -eq 0) {
                $FinalBackupPath += $Path
            }

            if ($Path.Count -eq 1 -and $FileCount -gt 1) {
                for ($i = 0; $i -lt ($FileCount - 1); $i++) {
                    $FinalBackupPath += $FinalBackupPath[0]
                }
            }

            if ($StorageBaseUrl -or $StorageCredential -or $isdestlinux) {
                $slash = "/"
            } else {
                $slash = "\"
            }

            if ($FinalBackupPath.Count -gt 1) {
                $File = New-Object System.IO.FileInfo($BackupFinalName)
                for ($i = 0; $i -lt $FinalBackupPath.Count; $i++) {
                    $FinalBackupPath[$i] = $FinalBackupPath[$i] + $slash + ("$($i+1)-" * $IncrementPrefix.ToBool() ) + $($File.BaseName) + "-$($i+1)-of-$FileCount.$suffix"
                }
""";
}
