#nullable enable

namespace Dataplat.Dbatools.Commands;

/// <summary>Hop script constants for BackupDbaDatabaseCommand (400-line file rule split;
/// generated by migration/tools/Build-W3004Partials.py from the verbatim source fragments -
/// regenerate, never hand-edit).</summary>
public sealed partial class BackupDbaDatabaseCommand
{
    private const string ProcessScriptTail = """
            } elseif ($FinalBackupPath[0] -ne 'NUL:') {
                $FinalBackupPath[0] = $FinalBackupPath[0] + $slash + $BackupFinalName
            }

            # Auto-detect dbname token in the directory path to prevent duplication when using CreateFolder + ReplaceInName
            if ($CreateFolder -and $ReplaceInName -and -not $NoAppendDbNameInPath) {
                $containsDbNameToken = $false
                foreach ($pathToCheck in $FinalBackupPath) {
                    $directoryPathToCheck = Split-Path -Path $pathToCheck -Parent
                    if ($directoryPathToCheck -and $directoryPathToCheck -match "(^|[\\/])dbname([\\/]|$)") {
                        $containsDbNameToken = $true
                        break
                    }
                }
                if ($containsDbNameToken) {
                    Write-Message -Level Verbose -Message "Directory path contains 'dbname' token with ReplaceInName. Automatically skipping database folder creation to prevent duplication." -FunctionName Backup-DbaDatabase
                    $NoAppendDbNameInPath = $true
                }
            }

            if ($CreateFolder -and $FinalBackupPath[0] -ne 'NUL:') {
                for ($i = 0; $i -lt $FinalBackupPath.Count; $i++) {
                    $parent = [IO.Path]::GetDirectoryName($FinalBackupPath[$i])
                    $leaf = [IO.Path]::GetFileName($FinalBackupPath[$i])
                    if ($NoAppendDbNameInPath) {
                        $FinalBackupPath[$i] = [IO.Path]::Combine($parent, $leaf)
                    } else {
                        $FinalBackupPath[$i] = [IO.Path]::Combine($parent, $dbName, $leaf)
                    }
                }
            }

            if ($True -eq $ReplaceInName) {
                for ($i = 0; $i -lt $FinalBackupPath.count; $i++) {
                    $FinalBackupPath[$i] = $FinalBackupPath[$i] -replace ('dbname', $dbName)
                    $FinalBackupPath[$i] = $FinalBackupPath[$i] -replace ('instancename', $server.ServiceName)
                    $FinalBackupPath[$i] = $FinalBackupPath[$i] -replace ('servername', $server.ComputerName)
                    $FinalBackupPath[$i] = $FinalBackupPath[$i] -replace ('timestamp', $timestamp)
                    $FinalBackupPath[$i] = $FinalBackupPath[$i] -replace ('backuptype', $outputType)
                }
            }

            # Linux can't support making new directories yet, and it's likely that databases
            # will be in one place
            if (-not $IgnoreFileChecks -and -not $StorageBaseUrl -and -not $isdestlinux) {
                $parentPaths = ($FinalBackupPath | ForEach-Object { Split-Path $_ } | Select-Object -Unique)
                foreach ($parentPath in $parentPaths) {
                    if (-not (Test-DbaPath -SqlInstance $server -Path $parentPath)) {
                        if (($BuildPath -eq $true) -or ($CreateFolder -eq $True)) {
                            $null = New-DbaDirectory -SqlInstance $server -Path $parentPath
                        } else {
                            $failreason += "SQL Server cannot check if $parentPath exists. You can try disabling this check with -IgnoreFileChecks"
                            $failures += $failreason
                            Write-Message -Level Warning -Message "$failreason" -FunctionName Backup-DbaDatabase
                        }
                    }
                }
            }

            # Because of #7860, don't use [IO.Path]::GetFullPath on MacOS
            if ($null -eq $StorageBaseUrl -and $Path -and -not $nonwindows -and -not $isdestlinux) {
                $FinalBackupPath = $FinalBackupPath | ForEach-Object { [IO.Path]::GetFullPath($_) }
            }


            $script = $null
            $backupComplete = $false

            if (!$failures) {
                $FileCount = $FinalBackupPath.Count

                foreach ($backupfile in $FinalBackupPath) {
                    $device = New-Object Microsoft.SqlServer.Management.Smo.BackupDeviceItem
                    if ($null -ne $StorageBaseUrl) {
                        $device.DeviceType = "URL"
                    } else {
                        $device.DeviceType = "File"
                    }

                    if ($WithFormat) {
                        Write-Message -Message "WithFormat specified. Ensuring Initialize and SkipTapeHeader are set to true." -Level Verbose -FunctionName Backup-DbaDatabase
                        $Initialize = $true
                        $SkipTapeHeader = $true
                    }

                    $backup.FormatMedia = $WithFormat
                    $backup.Initialize = $Initialize
                    $backup.SkipTapeHeader = $SkipTapeHeader
                    $device.Name = $backupfile
                    $backup.Devices.Add($device)
                }
                $humanBackupFile = $FinalBackupPath -Join ','
                Write-Message -Level Verbose -Message "Devices added" -FunctionName Backup-DbaDatabase
                $percent = [Microsoft.SqlServer.Management.Smo.PercentCompleteEventHandler] {
                    Write-Progress -Id $ProgressId -Activity "Backing up database $dbName to $humanBackupFile" -PercentComplete $_.Percent -Status ([System.String]::Format("Progress: {0} %", $_.Percent))
                }
                $backup.add_PercentComplete($percent)
                $backup.PercentCompleteNotification = 1
                $backup.add_Complete($complete)

                if ($MaxTransferSize) {
                    $backup.MaxTransferSize = $MaxTransferSize
                }
                if ($BufferCount) {
                    $backup.BufferCount = $BufferCount
                }
                if ($BlockSize) {
                    $backup.Blocksize = $BlockSize
                }

                Write-Progress -Id $ProgressId -Activity "Backing up database $dbName to $humanBackupFile" -PercentComplete 0 -Status ([System.String]::Format("Progress: {0} %", 0))

                try {
                    if ($__realCmdlet.ShouldProcess($server.Name, "Backing up $dbName to $humanBackupFile")) {
                        if ($OutputScriptOnly -ne $True) {
                            # Check if we need to use T-SQL execution for S3 with BACKUP_OPTIONS
                            if ($isS3Backup -and $StorageRegion) {
                                # Generate script first, then append BACKUP_OPTIONS and execute via T-SQL
                                $script = $backup.Script($server)
                                $backupOptionsJson = "{`"s3`": {`"region`":`"$StorageRegion`"}}"
                                $script += ", BACKUP_OPTIONS = '$backupOptionsJson'"
                                Write-Message -Level Verbose -Message "Executing S3 backup with BACKUP_OPTIONS for region: $StorageRegion" -FunctionName Backup-DbaDatabase
                                $null = $server.ConnectionContext.ExecuteNonQuery($script)
                            } else {
                                $backup.SqlBackup($server)
                                $script = $backup.Script($server)
                            }
                            Write-Progress -Id $ProgressId -Activity "Backing up database $dbName to $backupfile" -Completed
                            $BackupComplete = $true
                            if ($server.VersionMajor -eq '8') {
                                $HeaderInfo = Get-BackupAncientHistory -SqlInstance $server -Database $dbName
                            } else {
                                $HeaderInfo = Get-DbaDbBackupHistory -SqlInstance $server -Database $dbName @gbhSwitch -IncludeCopyOnly -RecoveryFork $db.RecoveryForkGuid | Sort-Object -Property End -Descending | Select-Object -First 1
                            }
                            $Filelist = @()
                            $FileList += $Headerinfo.FileList | Where-Object { $_.FileType -eq "D" } | Select-Object FileType, LogicalName , PhysicalName, @{ Name = "Type"; Expression = { "D" } }
                            $FileList += $Headerinfo.FileList | Where-Object { $_.FileType -eq "L" } | Select-Object FileType, LogicalName , PhysicalName, @{ Name = "Type"; Expression = { "L" } }

                            $Verified = $false
                            if ($Verify) {
                                $verifiedresult = [PSCustomObject]@{
                                    ComputerName         = $server.ComputerName
                                    InstanceName         = $server.ServiceName
                                    SqlInstance          = $server.DomainInstanceName
                                    DatabaseName         = $dbName
                                    BackupComplete       = $BackupComplete
                                    BackupFilesCount     = $FinalBackupPath.Count
                                    BackupFile           = (Split-Path $FinalBackupPath -Leaf)
                                    BackupFolder         = (Convert-BackupPath -object (Split-Path $FinalBackupPath | Sort-Object -Unique))
                                    BackupPath           = ($FinalBackupPath | Sort-Object -Unique)
                                    Script               = $script
                                    Notes                = $failures -join (',')
                                    FullName             = ($FinalBackupPath | Sort-Object -Unique)
                                    FileList             = $FileList
                                    SoftwareVersionMajor = $server.VersionMajor
                                    Type                 = $outputType
                                    FirstLsn             = $HeaderInfo.FirstLsn
                                    DatabaseBackupLsn    = $HeaderInfo.DatabaseBackupLsn
                                    CheckPointLsn        = $HeaderInfo.CheckPointLsn
                                    LastLsn              = $HeaderInfo.LastLsn
                                    BackupSetId          = $HeaderInfo.BackupSetId
                                    LastRecoveryForkGUID = $HeaderInfo.LastRecoveryForkGUID
                                    EncryptorName        = $encryptionOptions.EncryptorName
                                    KeyAlgorithm         = $encryptionOptions.Algorithm
                                    EncruptorType        = $encryptionOptions.encryptorType
                                } | Restore-DbaDatabase -SqlInstance $server -DatabaseName DbaVerifyOnly -VerifyOnly -TrustDbBackupHistory -DestinationFilePrefix DbaVerifyOnly
                                if ($verifiedResult[0] -eq "Verify successful") {
                                    $failures += $verifiedResult[0]
                                    $Verified = $true
                                } else {
                                    $failures += $verifiedResult[0]
                                    $Verified = $false
                                }
                            }
                            $HeaderInfo | Add-Member -Type NoteProperty -Name BackupComplete -Value $BackupComplete
                            $HeaderInfo | Add-Member -Type NoteProperty -Name BackupFile -Value (Split-Path $FinalBackupPath -Leaf)
                            $HeaderInfo | Add-Member -Type NoteProperty -Name BackupFilesCount -Value $FinalBackupPath.Count
                            if ($FinalBackupPath[0] -eq 'NUL:') {
                                $pathresult = "NUL:"
                            } else {
                                $pathresult = (Split-Path $FinalBackupPath | Sort-Object -Unique)
                                if ($isdestlinux -and $pathresult) {
                                    $pathresult = $pathresult.Replace("\", "/")
                                } elseif ($pathresult) {
                                    $pathresult = $pathresult.Replace("/", "\")
                                }
                            }
                            $HeaderInfo | Add-Member -Type NoteProperty -Name BackupFolder -Value $pathresult
                            $HeaderInfo | Add-Member -Type NoteProperty -Name BackupPath -Value ($FinalBackupPath | Sort-Object -Unique)
                            $HeaderInfo | Add-Member -Type NoteProperty -Name DatabaseName -Value $dbName
                            $HeaderInfo | Add-Member -Type NoteProperty -Name Notes -Value ($failures -join (','))
                            $HeaderInfo | Add-Member -Type NoteProperty -Name Script -Value $script
                            $HeaderInfo | Add-Member -Type NoteProperty -Name Verified -Value $Verified
                        } else {
                            $script = $backup.Script($server)
                            # Append BACKUP_OPTIONS for S3 with region
                            if ($isS3Backup -and $StorageRegion) {
                                $backupOptionsJson = "{`"s3`": {`"region`":`"$StorageRegion`"}}"
                                $script += ", BACKUP_OPTIONS = '$backupOptionsJson'"
                            }
                            $script
                            Write-Progress -Id $ProgressId -Activity "Backing up database $dbName to $backupfile" -Completed
                        }
                    }
                } catch {
                    if ($NoRecovery -and ($_.Exception.InnerException.InnerException.InnerException -like '*cannot be opened. It is in the middle of a restore.')) {
                        Write-Message -Message "Exception thrown by db going into restoring mode due to recovery" -Level Verbose -FunctionName Backup-DbaDatabase
                    } else {
                        Write-Progress -Id $ProgressId -Activity "Backup" -Completed
                        Write-Progress -Id $topProgressId -Activity "Backup" -Completed
                        Stop-Function -message "Backup of [$dbName] failed" -ErrorRecord $_ -Target $dbName -Continue -FunctionName Backup-DbaDatabase
                        $BackupComplete = $false
                    }
                }
            }
            Write-Progress -Id $topProgressId -Activity 'Backup' -Completed

            $OutputExclude = 'FullName', 'FileList', 'SoftwareVersionMajor'

            if ($failures.Count -eq 0) {
                $OutputExclude += ('Notes', 'FirstLsn', 'DatabaseBackupLsn', 'CheckpointLsn', 'LastLsn', 'BackupSetId', 'LastRecoveryForkGuid')
            }

            $headerinfo | Select-DefaultView -ExcludeProperty $OutputExclude

            if (-not $ReplaceInName) {
                $FilePath = $null
            }
        }
    }
    @{ __w3004State = @{ TimeStampFormat = $TimeStampFormat; BlockSize = $BlockSize; MaxTransferSize = $MaxTransferSize; isS3Backup = $isS3Backup; Path = $Path; FilePath = $FilePath; FileCount = $FileCount; StorageBaseUrl = $StorageBaseUrl; IgnoreFileChecks = $IgnoreFileChecks; Initialize = $Initialize; SkipTapeHeader = $SkipTapeHeader; NoAppendDbNameInPath = $NoAppendDbNameInPath; CopyOnly = $CopyOnly; isdir = $isdir; failreason = $failreason; Description = $Description; HeaderInfo = $HeaderInfo; InputObject = $InputObject; psbpHasPath = $PSBoundParameters.ContainsKey("Path"); psbpPath = $PSBoundParameters["Path"]; psbpHasFilePath = $PSBoundParameters.ContainsKey("FilePath"); psbpFilePath = $PSBoundParameters["FilePath"]; interrupted = (Test-FunctionInterrupt) } }
} $SqlInstance $SqlCredential $Database $ExcludeDatabase $Path $FilePath $IncrementPrefix $ReplaceInName $NoAppendDbNameInPath $CopyOnly $Type $CreateFolder $FileCount $CompressBackup $Checksum $Verify $MaxTransferSize $BlockSize $BufferCount $StorageBaseUrl $StorageCredential $StorageRegion $NoRecovery $BuildPath $WithFormat $Initialize $SkipTapeHeader $TimeStampFormat $IgnoreFileChecks $OutputScriptOnly $EncryptionAlgorithm $EncryptionCertificate $Description $InputObject $EnableException $__state $__hopInterrupted $__realBoundParameters $__realCmdlet $__boundWhatIf $__boundConfirm $__boundVerbose $__boundDebug @__commonParameters 3>&1 2>&1
""";
}
