using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Dataplat.Dbatools.Csv.Reader;

namespace Dataplat.Dbatools.Csv.Tests
{
    public partial class CsvSchemaInferenceTest
    {

        [TestMethod]
        public void TestInferSchema_GzipCompressed()
        {
            string csvPath = Path.Combine(_tempDir, "data.csv.gz");
            string csvContent = @"Id,Name,Value
1,Test,100
2,Demo,200
3,Sample,300
";
            using (var fs = File.Create(csvPath))
            using (var gz = new GZipStream(fs, CompressionMode.Compress))
            using (var writer = new StreamWriter(gz))
            {
                writer.Write(csvContent);
            }

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            Assert.AreEqual(3, columns.Count);
            Assert.AreEqual("int", columns[0].SqlDataType);
            Assert.IsTrue(columns[1].SqlDataType.StartsWith("varchar("));
            Assert.AreEqual("int", columns[2].SqlDataType);
        }



        [TestMethod]
        public void TestInferSchema_CustomDelimiter()
        {
            string csvPath = Path.Combine(_tempDir, "semicolon.csv");
            File.WriteAllText(csvPath, @"Id;Name;Value
1;John;100
2;Jane;200
");

            var options = new CsvReaderOptions { Delimiter = ";" };
            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath, options);

            Assert.AreEqual(3, columns.Count);
            Assert.AreEqual("Id", columns[0].ColumnName);
            Assert.AreEqual("Name", columns[1].ColumnName);
            Assert.AreEqual("Value", columns[2].ColumnName);
        }

        [TestMethod]
        public void TestInferSchema_TabDelimited()
        {
            string csvPath = Path.Combine(_tempDir, "tabs.tsv");
            File.WriteAllText(csvPath, "Id\tName\tValue\n1\tJohn\t100\n2\tJane\t200\n");

            var options = new CsvReaderOptions { Delimiter = "\t" };
            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath, options);

            Assert.AreEqual(3, columns.Count);
            Assert.AreEqual("int", columns[0].SqlDataType);
        }

        [TestMethod]
        public void TestInferSchema_CustomDateFormat()
        {
            string csvPath = Path.Combine(_tempDir, "customdate.csv");
            File.WriteAllText(csvPath, @"Id,Date
1,25-Dec-2024
2,15-Jan-2025
3,01-Feb-2025
");

            var options = new CsvReaderOptions
            {
                DateTimeFormats = new[] { "dd-MMM-yyyy" }
            };
            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath, options);

            Assert.AreEqual("datetime2", columns[1].SqlDataType);
        }

        [TestMethod]
        public void TestInferSchema_NoHeaderRow()
        {
            string csvPath = Path.Combine(_tempDir, "noheader.csv");
            File.WriteAllText(csvPath, @"1,John,100
2,Jane,200
3,Bob,300
");

            var options = new CsvReaderOptions { HasHeaderRow = false };
            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath, options);

            Assert.AreEqual(3, columns.Count);
            // Column names are auto-generated by CsvDataReader (0-based: Column0, Column1, Column2)
            Assert.AreEqual("Column0", columns[0].ColumnName);
            Assert.AreEqual("Column1", columns[1].ColumnName);
            Assert.AreEqual("Column2", columns[2].ColumnName);
        }



        [TestMethod]
        public void TestInferSchema_EmptyFile()
        {
            string csvPath = Path.Combine(_tempDir, "empty.csv");
            File.WriteAllText(csvPath, "");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            Assert.AreEqual(0, columns.Count);
        }

        [TestMethod]
        public void TestInferSchema_HeaderOnly()
        {
            string csvPath = Path.Combine(_tempDir, "headeronly.csv");
            File.WriteAllText(csvPath, "Id,Name,Value\n");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            Assert.AreEqual(3, columns.Count);
            Assert.AreEqual("varchar(1)", columns[0].SqlDataType);
            Assert.IsTrue(columns[0].IsNullable);
        }

        [TestMethod]
        public void TestInferSchema_SingleRow()
        {
            string csvPath = Path.Combine(_tempDir, "singlerow.csv");
            File.WriteAllText(csvPath, "Id,Name,Value\n1,Test,100\n");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            Assert.AreEqual(3, columns.Count);
            Assert.AreEqual("int", columns[0].SqlDataType);
            Assert.AreEqual(1, columns[0].TotalCount);
        }

        [TestMethod]
        public void TestInferSchema_ScientificNotation()
        {
            string csvPath = Path.Combine(_tempDir, "scientific.csv");
            File.WriteAllText(csvPath, @"Value,BigValue
1.5e2,1.0E10
2.5e2,2.0E10
3.5e2,3.0E10
");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            // Scientific notation should be handled
            Assert.IsTrue(columns[0].SqlDataType.Contains("decimal") ||
                          columns[0].SqlDataType.StartsWith("varchar("));
        }

        [TestMethod]
        public void TestInferSchema_MixedTypesInColumn_FallsBackToVarchar()
        {
            string csvPath = Path.Combine(_tempDir, "mixed.csv");
            File.WriteAllText(csvPath, @"Value
100
abc
200
");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            Assert.IsTrue(columns[0].SqlDataType.StartsWith("varchar("));
        }

        [TestMethod]
        public void TestInferSchema_QuotedFields()
        {
            string csvPath = Path.Combine(_tempDir, "quoted.csv");
            // RFC 4180: quotes inside quoted fields are escaped by doubling them
            var sb = new StringBuilder();
            sb.AppendLine("Id,Name,Description");
            sb.AppendLine("1,\"John Smith\",\"A \"\"quoted\"\" value\"");
            sb.AppendLine("2,\"Jane Doe\",\"Another, with comma\"");
            File.WriteAllText(csvPath, sb.ToString());

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            Assert.AreEqual(3, columns.Count);
            Assert.IsTrue(columns[2].MaxLength > 10); // Should capture full quoted content
        }

        [TestMethod]
        public void TestInferSchema_LeadingZeros_ParseAsInteger()
        {
            string csvPath = Path.Combine(_tempDir, "leadingzeros.csv");
            File.WriteAllText(csvPath, @"ZipCode,Phone
01234,0123456789
02345,0234567890
");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            // Leading zeros are parsed successfully by int.TryParse (01234 -> 1234)
            // so the column is inferred as integer. Note: the leading zeros are NOT
            // preserved in the parsed value. If preserving leading zeros is required,
            // callers should override the inferred type to varchar.
            Assert.AreEqual("int", columns[0].SqlDataType);
            Assert.AreEqual("int", columns[1].SqlDataType); // 0123456789 fits in int (< 2.1 billion)
        }

        [TestMethod]
        public void TestInferSchema_DecimalWithNoIntegerPart()
        {
            string csvPath = Path.Combine(_tempDir, "decimalnoint.csv");
            File.WriteAllText(csvPath, @"Value,Tiny,Mixed
.5,.001,.999
.25,.002,1.5
.125,.003,10.25
");

            var columns = CsvSchemaInference.InferSchemaFromSample(csvPath);

            // Decimals without integer part (e.g., .5 instead of 0.5) should be handled
            Assert.IsTrue(columns[0].SqlDataType.Contains("decimal"), String.Format("Expected decimal, got {0}", columns[0].SqlDataType));
            Assert.IsTrue(columns[1].SqlDataType.Contains("decimal"), String.Format("Expected decimal, got {0}", columns[1].SqlDataType));
            Assert.IsTrue(columns[2].SqlDataType.Contains("decimal"), String.Format("Expected decimal, got {0}", columns[2].SqlDataType));

            // Verify scale is tracked correctly
            Assert.AreEqual(3, columns[0].Scale); // .5, .25, .125 -> max 3 digits after decimal
            Assert.AreEqual(3, columns[1].Scale); // .001, .002, .003 -> 3 digits after decimal
        }

    }
}
